### ISSUE TITLE
Error Fix: NullPointerException when running Admin Commands

### ISSUE THREAD

**Issue by lehenbnw** [tbackus127/RathBot#15]
Stack Trace:

```Java
10:14:12.275: [ERROR][Event Dispatcher Handler][sx.blah.discord.Discord4J] - Unhandled exception caught dispatching event MessageReceivedEvent
java.lang.NullPointerException
	at com.rath.rathbot.RathBot.kickUser(RathBot.java:151)
	at com.rath.rathbot.cmd.disc.actions.KickCmd.executeCommand(KickCmd.java:88)
	at com.rath.rathbot.CommandParser.parseCommand(CommandParser.java:81)
	at com.rath.rathbot.EventHandler.onMessageReceived(EventHandler.java:46)
	at sx.blah.discord.api.events.EventDispatcher$MethodEventHandler.handle(EventDispatcher.java:680)
	at sx.blah.discord.api.events.EventDispatcher.lambda$null$17(EventDispatcher.java:610)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by tbackus127** [comment]
Done.
